apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealm-editor-role
rules:
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakrealms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakrealms/status
  verbs:
  - get
